version: "2"

run:
  timeout: 5m

linters:
  default: none

  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gocritic

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    gocritic:
      enabled-checks:
        - appendAssign
        - argOrder
        - badCond
        - caseOrder
        - dupArg
        - dupBranchBody
        - dupCase
